### ISSUE TITLE
 list index out of range

### ISSUE THREAD

**Issue by balabalabalading** [AayushG159/NotionToObsidian#3]
mr.h@huzichundeMacBook-Pro ~ % cd /Users/mr.h/Downloads/NotionToObsidian-main/src
mr.h@huzichundeMacBook-Pro src % python main.py
20-Apr-23 07:25:25 - migrate - INFO - Initiating notion to obsidian notes migration
20-Apr-23 07:25:25 - migrate - INFO - Traversing, storing UUIDs from file names, renaming files
20-Apr-23 07:25:31 - migrate - INFO - Complete
20-Apr-23 07:25:31 - migrate - INFO - Removing UUIDs from files and formatting notion DB data
Traceback (most recent call last):
  File "/Users/mr.h/Downloads/NotionToObsidian-main/src/main.py", line 9, in <module>
    migrate.start_migration()
  File "/Users/mr.h/Downloads/NotionToObsidian-main/src/migrate.py", line 38, in start_migration
    self.format_files()
  File "/Users/mr.h/Downloads/NotionToObsidian-main/src/migrate.py", line 140, in format_files
    convert_notion_db_data(file, self.root_loc)
  File "/Users/mr.h/Downloads/NotionToObsidian-main/src/notion_db.py", line 50, in convert_notion_db_data
    file_data[index[-1]] = file_data[index[-1]].rstrip() + '\n' + tag_property + front_matter_str
IndexError: list index out of range

**Comment by Sinled** [comment]
Also have this problem

**Comment by AayushG159** [comment]
Can you make the following change to `logging_config.py` and share the logs again:

Old:
`logging.basicConfig(level=logging.INFO, format='%(asctime)s - %(name)s - %(levelname)s - %(message)s', datefmt='%d-%b-%y %H:%M:%S')`

New:
`logging.basicConfig(level=logging.DEBUG, format='%(asctime)s - %(name)s - %(levelname)s - %(message)s', datefmt='%d-%b-%y %H:%M:%S')`

Also, make sure to not run again on the same export, as it's not made to be robust. It will unnecessarily truncate paths and files.

**Comment by AayushG159** [comment]
Closing the issue due to inactivity
